DROP PROCEDURE IF EXISTS addNSFW;
GO

CREATE PROCEDURE addNSFW
	@link TEXT
AS

BEGIN TRANSACTION;

INSERT INTO bank(link) VALUES(@link);
INSERT INTO nsfw SELECT id FROM bank WHERE link LIKE @link;

COMMIT;
GO